### ISSUE TITLE
How-to

### ISSUE THREAD

**Issue by T81** [Andreas-Siemens/InfluxDB-v2-LabVIEW-Client#2]
How to use it in an existing project? 
Assuming I have an existing project, which is the proper way to add the client to it?
Copy the files? Import the library?
A detailed 1-2-3 installation steps would be useful

**Comment by Andreas-Siemens** [comment]
Before you start make sure that you have installed the i3 JSON Toolkit. You can download this toolkit from the [VIPM Homepage](https://www.vipm.io/package/i3_json/?utm_source=vipm_desktop)

For an existing project just copy the folder "InfluxDB v2 Client" into your project directory and add the "InfluxDB v2 Client.lvlib" to your project tree. That's all.

If you want to study how to use the "InfluxDB v2 Client.lvlib" then copy also the "Examples" folder and add it to your project tree too. With the VI "Test v2 Client.vi"  it is a good place to start from.

**Comment by T81** [comment]
Thanks for explaining
